# Generated by Django 5.1.1 on 2024-09-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labbooking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("formula", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
            ],
        ),
    ]
