# Generated by Django 5.1.1 on 2024-09-12 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labbooking", "0002_chemical"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="is_available",
            new_name="availability",
        ),
        migrations.RemoveField(
            model_name="antibody",
            name="description",
        ),
        migrations.RemoveField(
            model_name="antibody",
            name="file",
        ),
        migrations.RemoveField(
            model_name="protocol",
            name="antibody",
        ),
        migrations.RemoveField(
            model_name="protocol",
            name="content",
        ),
        migrations.AddField(
            model_name="antibody",
            name="concentration",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="species",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="experiment",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="experiment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protocol",
            name="description",
            field=models.TextField(default="Default description"),
        ),
        migrations.AddField(
            model_name="protocol",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
